const main = async () => {
  console.log('Hello, World!');
};

main().catch((error) => {
  console.error('FATAL ERROR:', error);
});
